apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: techcommerce
data:
  API_BASE_URL: "http://product-api.techcommerce.svc.cluster.local:5000"
  ORDER_API_URL: "http://order-api.techcommerce.svc.cluster.local:4000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: techcommerce
data:
  LOG_LEVEL: "info"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: techcommerce
data:
  LOG_LEVEL: "info"
