apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: techcommerce
type: Opaque
data:
  DB_USER: ZGJfdXNlcg==        # "db_user" base64
  DB_PASSWORD: c3VwZXJzZWNyZXQ= # "supersecret" base64
  API_KEY: c29tZS1hcGkta2V5     # "some-api-key"
