apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: techcommerce
type: Opaque
data:
  DB_USER: ZGJfdXNlcg==        
  DB_PASSWORD: c3VwZXJzZWNyZXQ= 
  API_KEY: c29tZS1hcGkta2V5    
