apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: techcommerce
spec:
  selector:
    app: product-api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
