apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: techcommerce
spec:
  selector:
    app: order-api
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
